Vagrant.configure("2") do |config|
  (1..2).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.box = "centos/7"
      node.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", "512", "--cpus", "1", "--name", "web-#{i}"]
       end
      node.vm.network "private_network", type: "dhcp"
      node.vm.provision "file", source: "./sc.sh", destination: "sc.sh"
      node.vm.provision "shell",
        inline: "chmod +x sc.sh && ./sc.sh", run: 'always'
    end
  end    
end
